### ISSUE TITLE
Auth/OpenID/CryptUtil.php : replace mt_rand() by something better

### ISSUE THREAD

**Issue by Wikinaut** [openid/php-openid#112]
- http://www.php.net/manual/en/function.mt-rand.php 
- http://www.openwall.com/php_mt_seed/

Because mt_rand only uses 32-bit seeds, the use is deprecated. http://www.php.net/manual/en/function.mt-rand.php recommends the use of  openssl_random_pseudo_bytes() .

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
