### ISSUE TITLE
Release a version

### ISSUE THREAD

**Issue by relaxnow** [openid/php-openid#119]
With all due respect, promises were made in #116 and #102 to release a version, but nothing has happened so far.
Maybe I'm missing something because this seems like a really quick win?

**Comment by aztech-dev** [comment]
:+1: would be nice

**Comment by sirdiego** [comment]
Now with the recent PHP7 PR (#130) it would be awesome to have a new version for composer usage.

**Comment by vitman** [comment]
and still no new version..

**Comment by adhocore** [comment]
looking forward for a new version :)
