### ISSUE TITLE
detect.php says that An unexpected URL was returned 

### ISSUE THREAD

**Issue by laptander** [openid/php-openid#127]
I do not know if it is really bug, but when I open example/detect.php I am getting

```
HTTP Fetching

This PHP installation has support for libcurl. Good.

An HTTP request was completed. An unexpected URL was returned: https://gist.githubusercontent.com/chuckpearce/6810258/raw/c57eff55ebc0c54973903af5f72bac72762cf4f4/gistfile1.txt.

Your PHP installation appears to support SSL, so it will be able to process HTTPS identity URLs and server URLs.
```

But if I replace in examples/detect.php 
$fetch_url = 'https://gist.github.com/chuckpearce/6810258/raw/c57eff55ebc0c54973903af5f72bac72762cf4f4/gistfile1.txt';
with
$fetch_url = 'https://gist.githubusercontent.com/chuckpearce/6810258/raw/c57eff55ebc0c54973903af5f72bac72762cf4f4/gistfile1.txt';
all works fine and I get Setup Complete!

I think maybe github changed their infrastructure (redirecting from gist.github.com to gist.githubusercontent.com) or maybe my setup is some kind wrond.

Any suggestions?

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
