### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by tbannister** [openid/php-openid#129]
It looks like this library will not work with PHP7 since PHP4 style constructors are no longer allowed.

**Comment by tokushima** [comment]
from PHP4 style constructors it has been changed to __construct.
I think that different from the main branch.

**Comment by tbannister** [comment]
php7cc Report:
File: php-openid/Tests/Auth/OpenID/Server.php
> Line 1535: PHP 4 constructors are now deprecated
    function _MockSignatory($assoc)
    {
    }
> Line 2022: PHP 4 constructors are now deprecated
    function Counter()
    {
    }
> Line 2141: String containing number in hexadecimal notation
    '0x3999';
> Line 2445: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Server()
    {
    }


File: php-openid/Tests/Auth/OpenID/StoreTest.php
> Line 699: Result of new is assigned by reference
    $store =& new \Auth_OpenID_MDB2Store($db);
> Line 754: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_StoreTest()
    {
    }


File: php-openid/Tests/Auth/OpenID/AuthRequest.php
> Line 291: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_AuthRequest()
    {
    }


File: php-openid/Tests/Auth/OpenID/HMAC.php
> Line 21: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_HMAC_TestCase($name, $key, $data, $expected, $hmac_func)
    {
    }
> Line 134: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_HMAC($name)
    {
    }


File: php-openid/Tests/Auth/OpenID/Parse.php
> Line 20: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Link($case)
    {
    }
> Line 88: PHP 4 constructors are now deprecated
    function NumTestCases($test_cases, $num_tests)
    {
    }
> Line 171: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Parse()
    {
    }


File: php-openid/Tests/Auth/OpenID/TrustRoot.php
> Line 11: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_TRParseCase($desc, $case, $expected)
    {
    }
> Line 39: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_TRMatchCase($desc, $tr, $rt, $matches)
    {
    }
> Line 158: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_TrustRoot($name)
    {
    }


File: php-openid/Tests/Auth/OpenID/BigMath.php
> Line 23: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_BinLongConvertRnd($lib, $max)
    {
    }
> Line 48: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_BinLongConvert($lib, $bin, $lng)
    {
    }
> Line 69: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Base64ToLong($lib, $b64, $num)
    {
    }
> Line 84: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_LongToBase64($lib, $b64, $num)
    {
    }
> Line 99: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Rand($lib)
    {
    }
> Line 219: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_BigMath($name)
    {
    }


File: php-openid/Tests/Auth/OpenID/Consumer.php
> Line 44: PHP 4 constructors are now deprecated
    function FastConsumerSession($dh = null)
    {
    }
> Line 111: PHP 4 constructors are now deprecated
    function Auth_OpenID_TestFetcher($user_url, $user_page, $assoc_secret, $assoc_handle)
    {
    }
> Line 995: PHP 4 constructors are now deprecated
    function _MockFetcher($response = null)
    {
    }
> Line 1527: Possible object property creation during by-reference assignment
    $this->consumer->fetcher =& $this->fetcher;
> Line 1616: Possible object property creation during by-reference assignment
    $this->consumer->fetcher =& $this->fetcher;
> Line 1784: PHP 4 constructors are now deprecated
    function _StubConsumer()
    {
    }
> Line 2092: Possible object property creation during by-reference assignment
    $this->consumer->check_endpoint =& $this->endpoint;


File: php-openid/Tests/Auth/OpenID/RPVerify.php
> Line 48: PHP 4 constructors are now deprecated
    function _MockDiscover($data)
    {
    }
> Line 222: PHP 4 constructors are now deprecated
    function Verifier($test_case, $return_to)
    {
    }
> Line 284: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_RPVerify()
    {
    }


File: php-openid/Tests/Auth/OpenID/Negotiation.php
> Line 339: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Negotiation()
    {
    }


File: php-openid/Tests/Auth/OpenID/SReg.php
> Line 42: PHP 4 constructors are now deprecated
    function FakeEndpoint($supported)
    {
    }
> Line 84: PHP 4 constructors are now deprecated
    function FakeMessage()
    {
    }
> Line 183: PHP 4 constructors are now deprecated
    function SentinelFakeMessage($test_case)
    {
    }
> Line 562: PHP 4 constructors are now deprecated
    function DummySuccessResponse($message, $signed_stuff)
    {
    }
> Line 661: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_SReg()
    {
    }


File: php-openid/Tests/Auth/OpenID/DiffieHellman.php
> Line 21: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_DiffieHellman_CheckCases($cases, $n)
    {
    }
> Line 34: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_DiffieHellman_Private($name, $input, $expected)
    {
    }
> Line 50: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_DiffieHellman_Exch($name, $p1, $p2, $shared)
    {
    }
> Line 117: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_DiffieHellman($name)
    {
    }


File: php-openid/Tests/Auth/OpenID/KVForm.php
> Line 58: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_KVForm_TestCase_Parse($arr, $str, $lossy, $errs)
    {
    }
> Line 100: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_KVForm_TestCase_Null($arr, $errs)
    {
    }
> Line 115: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_KVForm($name)
    {
    }


File: php-openid/Tests/Auth/OpenID/AX.php
> Line 520: PHP 4 constructors are now deprecated
    function FauxEndpoint()
    {
    }
> Line 780: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_AX()
    {
    }


File: php-openid/Tests/Auth/OpenID/Nonce.php
> Line 22: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Nonce()
    {
    }
> Line 98: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Nonce_TimestampCase($nonce_str, $skew, $now, $expected)
    {
    }
> Line 154: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Nonce_BadSplitCase($nonce_str)
    {
    }


File: php-openid/Tests/Auth/OpenID/PAPE.php
> Line 96: PHP 4 constructors are now deprecated
    function PAPE_DummySuccessResponse($message, $signed_stuff)
    {
    }
> Line 238: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_PAPE()
    {
    }


File: php-openid/Tests/Auth/OpenID/OpenID_Yadis.php
> Line 144: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Tester($uris, $type_uris, $delegate)
    {
    }
> Line 214: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_OpenID_Yadis()
    {
    }


File: php-openid/Tests/Auth/OpenID/VerifyDisco.php
> Line 55: PHP 4 constructors are now deprecated
    function _Tests_discoveryOverride($endpoint)
    {
    }


File: php-openid/Tests/Auth/OpenID/AssociationResponse.php
> Line 121: PHP 4 constructors are now deprecated
    function DummyAssocationSession($session_type, $allowed_assoc_types = array())
    {
    }


File: php-openid/Tests/Auth/OpenID/Discover_OpenID.php
> Line 16: PHP 4 constructors are now deprecated
    function _SimpleMockFetcher($responses)
    {
    }
> Line 63: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_DiscoveryFailure($responses)
    {
    }
> Line 100: PHP 4 constructors are now deprecated
    function _ErrorRaisingFetcher($thing_to_raise)
    {
    }
> Line 126: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_Discover_FetchException($exc)
    {
    }
> Line 154: PHP 4 constructors are now deprecated
    function _DiscoveryMockFetcher($documents)
    {
    }
> Line 539: PHP 4 constructors are now deprecated
    function _MockFetcherForXRIProxy($documents)
    {
    }
> Line 637: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_DiscoverSession()
    {
    }
> Line 689: PHP 4 constructors are now deprecated
    function _NonFetcher()
    {
    }


File: php-openid/Tests/Auth/OpenID/MemStore.php
> Line 10: PHP 4 constructors are now deprecated
    function ServerAssocs()
    {
    }
> Line 79: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_MemStore()
    {
    }


File: php-openid/Tests/Auth/OpenID/URINorm.php
> Line 21: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_URINorm_TestCase($name, $uri, $expected)
    {
    }
> Line 56: PHP 4 constructors are now deprecated
    function Tests_Auth_OpenID_URINorm($name)
    {
    }


File: php-openid/Tests/Auth/Yadis/XRI.php
> Line 134: PHP 4 constructors are now deprecated
    function Tests_Auth_Yadis_XRI()
    {
    }


File: php-openid/Tests/Auth/Yadis/Discover_Yadis.php
> Line 29: PHP 4 constructors are now deprecated
    function TestFetcher($base_url)
    {
    }
> Line 76: PHP 4 constructors are now deprecated
    function MockFetcher()
    {
    }
> Line 106: PHP 4 constructors are now deprecated
    function _TestCase($input_name, $id_name, $result_name, $success)
    {
    }
> Line 172: PHP 4 constructors are now deprecated
    function Tests_Auth_Yadis_Discover_Yadis()
    {
    }


File: php-openid/Tests/Auth/Yadis/ParseHTML.php
> Line 20: PHP 4 constructors are now deprecated
    function Tests_Auth_Yadis_ParseTest($case)
    {
    }
> Line 75: PHP 4 constructors are now deprecated
    function Tests_Auth_Yadis_ParseHTML()
    {
    }


File: php-openid/Tests/Auth/Yadis/Yadis.php
> Line 12: PHP 4 constructors are now deprecated
    function Tests_Auth_Yadis_DiscoveryTest($input_url, $redir_uri, $xrds_uri, $num)
    {
    }
> Line 71: PHP 4 constructors are now deprecated
    function Tests_Auth_Yadis_Yadis()
    {
    }


File: php-openid/contrib/signed_assertions/AP.php
> Line 45: PHP 4 constructors are now deprecated
    function Attribute_Provider($public_key_certificate, $private_key, $notBefore, $notOnOrAfter, $rsadsa, $acsURI, $assertionTemplate)
    {
    }


File: php-openid/Auth/OpenID/Server.php
> Line 151: PHP 4 constructors are now deprecated
    function Auth_OpenID_ServerError($message = null, $text = null, $reference = null, $contact = null)
    {
    }
> Line 295: PHP 4 constructors are now deprecated
    function Auth_OpenID_NoReturnToError($message = null, $text = 'No return_to URL available')
    {
    }
> Line 313: PHP 4 constructors are now deprecated
    function Auth_OpenID_MalformedReturnURL($message, $return_to)
    {
    }
> Line 326: PHP 4 constructors are now deprecated
    function Auth_OpenID_MalformedTrustRoot($message = null, $text = 'Malformed trust root')
    {
    }
> Line 356: PHP 4 constructors are now deprecated
    function Auth_OpenID_CheckAuthRequest($assoc_handle, $signed, $invalidate_handle = null)
    {
    }
> Line 466: PHP 4 constructors are now deprecated
    function Auth_OpenID_DiffieHellmanSHA1ServerSession($dh, $consumer_pubkey)
    {
    }
> Line 593: PHP 4 constructors are now deprecated
    function Auth_OpenID_AssociateRequest($session, $assoc_type)
    {
    }
> Line 766: PHP 4 constructors are now deprecated
    function Auth_OpenID_CheckIDRequest($identity, $return_to, $trust_root = null, $immediate = false, $assoc_handle = null, $server = null, $claimed_id = null)
    {
    }
> Line 1187: PHP 4 constructors are now deprecated
    function Auth_OpenID_ServerResponse($request)
    {
    }
> Line 1274: PHP 4 constructors are now deprecated
    function Auth_OpenID_WebResponse($code = null, $headers = null, $body = null)
    {
    }
> Line 1314: PHP 4 constructors are now deprecated
    function Auth_OpenID_Signatory($store)
    {
    }
> Line 1486: PHP 4 constructors are now deprecated
    function Auth_OpenID_SigningEncoder($signatory)
    {
    }
> Line 1524: PHP 4 constructors are now deprecated
    function Auth_OpenID_Decoder($server)
    {
    }
> Line 1607: PHP 4 constructors are now deprecated
    function Auth_OpenID_EncodingError($response)
    {
    }
> Line 1629: PHP 4 constructors are now deprecated
    function Auth_OpenID_UntrustedReturnURL($message, $return_to, $trust_root)
    {
    }
> Line 1682: PHP 4 constructors are now deprecated
    function Auth_OpenID_Server($store, $op_endpoint = null)
    {
    }


File: php-openid/Auth/OpenID/ServerRequest.php
> Line 31: PHP 4 constructors are now deprecated
    function Auth_OpenID_ServerRequest()
    {
    }


File: php-openid/Auth/OpenID/Association.php
> Line 131: PHP 4 constructors are now deprecated
    function Auth_OpenID_Association($handle, $secret, $issued, $lifetime, $assoc_type)
    {
    }
> Line 526: PHP 4 constructors are now deprecated
    function Auth_OpenID_SessionNegotiator($allowed_types)
    {
    }


File: php-openid/Auth/OpenID/Parse.php
> Line 111: PHP 4 constructors are now deprecated
    function Auth_OpenID_Parse()
    {
    }


File: php-openid/Auth/OpenID/Consumer.php
> Line 261: PHP 4 constructors are now deprecated
    function Auth_OpenID_Consumer($store, $session = null, $consumer_cls = null)
    {
    }
> Line 459: PHP 4 constructors are now deprecated
    function Auth_OpenID_DiffieHellmanSHA1ConsumerSession($dh = null)
    {
    }
> Line 614: PHP 4 constructors are now deprecated
    function Auth_OpenID_GenericConsumer($store)
    {
    }
> Line 1760: PHP 4 constructors are now deprecated
    function Auth_OpenID_AuthRequest($endpoint, $assoc)
    {
    }
> Line 2039: PHP 4 constructors are now deprecated
    function Auth_OpenID_SuccessResponse($endpoint, $message, $signed_args = null)
    {
    }
> Line 2142: PHP 4 constructors are now deprecated
    function Auth_OpenID_FailureResponse($endpoint, $message = null, $contact = null, $reference = null)
    {
    }
> Line 2167: PHP 4 constructors are now deprecated
    function Auth_OpenID_ServerErrorContainer($error_text, $error_code, $message)
    {
    }
> Line 2205: PHP 4 constructors are now deprecated
    function Auth_OpenID_CancelResponse($endpoint)
    {
    }
> Line 2231: PHP 4 constructors are now deprecated
    function Auth_OpenID_SetupNeededResponse($endpoint, $setup_url = null)
    {
    }


File: php-openid/Auth/OpenID/SQLStore.php
> Line 78: PHP 4 constructors are now deprecated
    function Auth_OpenID_SQLStore($connection, $associations_table = null, $nonces_table = null)
    {
    }


File: php-openid/Auth/OpenID/SReg.php
> Line 421: PHP 4 constructors are now deprecated
    function Auth_OpenID_SRegResponse($data = null, $sreg_ns_uri = Auth_OpenID_SREG_NS_URI)
    {
    }


File: php-openid/Auth/OpenID/DiffieHellman.php
> Line 50: PHP 4 constructors are now deprecated
    function Auth_OpenID_DiffieHellman($mod = null, $gen = null, $private = null, $lib = null)
    {
    }


File: php-openid/Auth/OpenID/PredisStore.php
> Line 48: PHP 4 constructors are now deprecated
    function Auth_OpenID_PredisStore(\Predis\Client $redis, $prefix = '')
    {
    }


File: php-openid/Auth/OpenID/DumbStore.php
> Line 53: PHP 4 constructors are now deprecated
    function Auth_OpenID_DumbStore($secret_phrase)
    {
    }


File: php-openid/Auth/OpenID/AX.php
> Line 72: PHP 4 constructors are now deprecated
    function Auth_OpenID_AX_Error($message = null)
    {
    }
> Line 154: PHP 4 constructors are now deprecated
    function Auth_OpenID_AX_AttrInfo($type_uri, $count, $required, $alias)
    {
    }
> Line 272: PHP 4 constructors are now deprecated
    function Auth_OpenID_AX_FetchRequest($update_url = null)
    {
    }
> Line 543: PHP 4 constructors are now deprecated
    function Auth_OpenID_AX_KeyValueMessage()
    {
    }
> Line 796: PHP 4 constructors are now deprecated
    function Auth_OpenID_AX_FetchResponse($update_url = null)
    {
    }
> Line 993: PHP 4 constructors are now deprecated
    function Auth_OpenID_AX_StoreResponse($succeeded = true, $error_message = null)
    {
    }


File: php-openid/Auth/OpenID/FileStore.php
> Line 49: PHP 4 constructors are now deprecated
    function Auth_OpenID_FileStore($directory)
    {
    }


File: php-openid/Auth/OpenID/PAPE.php
> Line 40: PHP 4 constructors are now deprecated
    function Auth_OpenID_PAPE_Request($preferred_auth_policies = null, $max_auth_age = null)
    {
    }
> Line 164: PHP 4 constructors are now deprecated
    function Auth_OpenID_PAPE_Response($auth_policies = null, $auth_time = null, $nist_auth_level = null)
    {
    }


File: php-openid/Auth/OpenID/Message.php
> Line 130: PHP 4 constructors are now deprecated
    function Auth_OpenID_Mapping($classic_array = null)
    {
    }
> Line 277: PHP 4 constructors are now deprecated
    function Auth_OpenID_NamespaceMap()
    {
    }
> Line 417: PHP 4 constructors are now deprecated
    function Auth_OpenID_Message($openid_namespace = null)
    {
    }


File: php-openid/Auth/OpenID/Discover.php
> Line 65: PHP 4 constructors are now deprecated
    function Auth_OpenID_ServiceEndpoint()
    {
    }


File: php-openid/Auth/OpenID/MDB2Store.php
> Line 65: PHP 4 constructors are now deprecated
    function Auth_OpenID_MDB2Store($connection, $associations_table = null, $nonces_table = null)
    {
    }


File: php-openid/Auth/OpenID/MemcachedStore.php
> Line 44: PHP 4 constructors are now deprecated
    function Auth_OpenID_MemcachedStore($connection, $compress = false)
    {
    }


File: php-openid/Auth/Yadis/Manager.php
> Line 283: PHP 4 constructors are now deprecated
    function Auth_Yadis_Manager($starting_url, $yadis_url, $services, $session_key)
    {
    }
> Line 390: PHP 4 constructors are now deprecated
    function Auth_Yadis_Discovery($session, $url, $session_key_suffix = null)
    {
    }


File: php-openid/Auth/Yadis/XRIRes.php
> Line 11: PHP 4 constructors are now deprecated
    function Auth_Yadis_ProxyResolver($fetcher, $proxy_url = null)
    {
    }


File: php-openid/Auth/Yadis/XML.php
> Line 137: PHP 4 constructors are now deprecated
    function Auth_Yadis_domxml()
    {
    }
> Line 220: PHP 4 constructors are now deprecated
    function Auth_Yadis_dom()
    {
    }


File: php-openid/Auth/Yadis/ParseHTML.php
> Line 46: PHP 4 constructors are now deprecated
    function Auth_Yadis_ParseHTML()
    {
    }


File: php-openid/Auth/Yadis/XRDS.php
> Line 88: PHP 4 constructors are now deprecated
    function Auth_Yadis_Service()
    {
    }
> Line 258: PHP 4 constructors are now deprecated
    function Auth_Yadis_XRDS($xmlParser, $xrdNodes)
    {
    }


File: php-openid/Auth/Yadis/Yadis.php
> Line 71: PHP 4 constructors are now deprecated
    function Auth_Yadis_DiscoveryResult($request_uri)
    {
    }


File: php-openid/Auth/Yadis/HTTPFetcher.php
> Line 26: PHP 4 constructors are now deprecated
    function Auth_Yadis_HTTPResponse($final_url = null, $status = null, $headers = null, $body = null)
    {
    }


File: php-openid/Auth/Yadis/ParanoidHTTPFetcher.php
> Line 30: PHP 4 constructors are now deprecated
    function Auth_Yadis_ParanoidHTTPFetcher()
    {
    }

Checked 103 files in 17.911 seconds

**Comment by Hast** [comment]
I have made a pull request #130
But I have no opportunity to check if it works correct. In fact, there are still some php7cc warnings in test scripts.
