### ISSUE TITLE
Why is new changes are not being released in new version?

### ISSUE THREAD

**Issue by vitman** [openid/php-openid#135]
Hi there,

as far as i can see the last version (2.3.0) was made in Jul 30, 2015. 
There is a lot of significant changes were made since that time(php 7 support for example).
Is there any reason why no new versions/tags was released since 2015?

I have  "openid/php-openid" : ">=2.0" in my composer.json, and i do not want to use dev-master in production environment, but necessary changes are not released.. why?

**Comment by J5lx** [comment]
Totally agree, though it would be nice to also have namespaces rather than Super_Long_ClassNames when that happens; after all at least 5.6 is required now anyway.

**Comment by marcoceppi** [comment]
I'm working on a branch that brings the whole library to 3.X and will start following strict [semver](http://semver.org/). I expect to have that ready and out in a few weeks

**Comment by J5lx** [comment]
Sounds good! How about replacing the prefixes with namespaces then? If I can find the time I’m happy to work on that myself. Maybe we could also attempt to “composerize” the library in general given how much of a de-facto standard composer has become, i.e. drop the manual requires in favour of the composer autoloader and adopt the one-class-per-file convention in the process, etc. What do you think about that?

**Comment by J5lx** [comment]
For reference, I’m going to start working on the namespaces because I really need some stupid routine work right now. I’ll also try to composerize the library as mentioned above (though I’ll have to think about what to do with all those loose functions and `define()`s), but I’ll keep that in (a) separate commit(s).

**Comment by marcoceppi** [comment]
Thanks, if you want to start a WIP pull request and branch that would be
great

**Comment by devicenull** [comment]
This is still a little terrifying to me, the last release was 3 years ago (and this bug has been open for a year)?

Is this still ready to be used in a production environment?

**Comment by reedy** [comment]
+1 here too

#129 would be lovely to get rid of logspam

As https://github.com/openid/php-openid/compare/2.3.0...master bumps PHP version from >= 4.3 to >= 5.6, this should probably be version 3.0.0

**Comment by marcoceppi** [comment]
It took longer than I projected, but I'm going to be cutting a 3.x this afternoon after a few more updates

**Comment by piranos** [comment]
got any update on that new release?
