### ISSUE TITLE
review plugin page

### ISSUE THREAD

**Issue by strk** [openid/php-openid#138]
This page needs to be updated:
https://wordpress.org/plugins/openid/#developers

In particular it has a broken "Browse the source" link pointing at an old SVN repository now dismissed..

**Comment by pfefferle** [comment]
This section can't be edited/changed, it is generated by WordPress.org but the SVN is not outdated, only limited. It is the repo we have to use to release new versions.

**Comment by pfefferle** [comment]
can you please add the issue to the wordpress-plugin repo next time, because I am no editor for this lib and might miss such issues. thanks :)

**Comment by strk** [comment]
Oops, sorry !
Correct place for this issue is https://github.com/diso/wordpress-openid/issues/49
