### ISSUE TITLE
examples/detect.php gives me a blank page

### ISSUE THREAD

**Issue by NathanHazout** [openid/php-openid#14]
I just downloaded the code, opened the README which says to first try to run the 'examples/detect.php'. 
The page redirects me to detect.php?test_query=a%26b, but loads a blank page. 'display_errors' is ON. 
Shouldn't this page work no matter what, as it is supposed to show me what's missing?
I'm running php 5.3 on a localhost.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
