### ISSUE TITLE
Auth_OpenID_ServerErrorContainer::$error_code is inaccessible

### ISSUE THREAD

**Issue by a-junpei** [openid/php-openid#142]
When using https://github.com/openid/php-openid/commit/263a6c7f299a71f5dd59a7feb2d62b93bb6a577c is later version, the following error occurs.

`PHP Fatal error:  Cannot access private property Auth_OpenID_ServerErrorContainer::$error_code in /****/vendor/openid/php-openid/Auth/OpenID/Consumer.php on line 1542, referer: ****`

It is due to private declared added with the following commits.
> https://github.com/openid/php-openid/commit/263a6c7f299a71f5dd59a7feb2d62b93bb6a577c#diff-a3eb6fadd1ca6b93c6a5d7505236c801R2295

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
