### ISSUE TITLE
Provide stable, clean release tarballs.

### ISSUE THREAD

**Issue by binki** [openid/php-openid#21]
The tarballs that github.com produces seem to be arbitrarily structured. May you post tarballs for php-openid releases at least slightly manually, such as having a subdirectory called packagename-version instead of username-reponame-commitid?

For example, ftp://ohnopub.net/mirror/php-openid-2.2.2.tar.bz2

Thanks.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
