### ISSUE TITLE
When will master branch add the function "blobDecode()" in MySQLStore.php?

### ISSUE THREAD

**Issue by carychow** [openid/php-openid#22]
It is very very very terrible that after I found this issue already happened when 2007! No one has fixed it until now!
You always get the "Bad signature" response if you don't make this change.

Please! Adds this function for the users who using MySQL (if this project is not dead).

```
public function blobDecode($blob)
{
    return pack('H*', substr($blob, 2));
}
```

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
