### ISSUE TITLE
Server denied check_authentication

### ISSUE THREAD

**Issue by pbrooks** [openid/php-openid#25]
On complete, I am getting the error:

object(Auth_OpenID_FailureResponse)#44 (6) {
  ["status"]=>
  string(7) "failure"
  ["endpoint"]=>
  NULL
  ["identity_url"]=>
  NULL
  ["message"]=>
  string(34) "Server denied check_authentication"
  ["contact"]=>
  NULL
  ["reference"]=>
  NULL
}

This is occurring in Consumer::_processCheckAuthReponse when getArg(Auth_OpenID_OpenID_NS, 'is_valid','false') is being passed.

The following data is in response:

Object(Auth_OpenID_Message)#57 (4) {
  ["allowed_openid_namespaces"]=>
  array(3) {
    [0]=>
    string(28) "http://openid.net/signon/1.0"
    [1]=>
    string(28) "http://openid.net/signon/1.1"
    [2]=>
    string(32) "http://specs.openid.net/auth/2.0"
  }
  ["args"]=>
  object(Auth_OpenID_Mapping)#41 (2) {
    ["keys"]=>
    array(1) {
      [0]=>
      array(2) {
        [0]=>
        string(32) "http://specs.openid.net/auth/2.0"
        [1]=>
        string(8) "is_valid"
      }
    }
    ["values"]=>
    array(1) {
      [0]=>
      string(5) "false"
    }
  }
  ["namespaces"]=>
  object(Auth_OpenID_NamespaceMap)#52 (3) {
    ["alias_to_namespace"]=>
    object(Auth_OpenID_Mapping)#49 (2) {
      ["keys"]=>
      array(1) {
        [0]=>
        string(14) "Null namespace"
      }
      ["values"]=>
      array(1) {
        [0]=>
        string(32) "http://specs.openid.net/auth/2.0"
      }
    }
    ["namespace_to_alias"]=>
    object(Auth_OpenID_Mapping)#51 (2) {
      ["keys"]=>
      array(1) {
        [0]=>
        string(32) "http://specs.openid.net/auth/2.0"
      }
      ["values"]=>
      array(1) {
        [0]=>
        string(14) "Null namespace"
      }
    }
    ["implicit_namespaces"]=>
    array(0) {
    }
  }
  ["_openid_ns_uri"]=>
  string(32) "http://specs.openid.net/auth/2.0"
}

Any ideas?

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
