### ISSUE TITLE
Please use trigger_error() instead of error_log()

### ISSUE THREAD

**Issue by GICodeWarrior** [openid/php-openid#26]
The log method should be modified to take a severity parameter (E_USER_NOTICE, E_USER_WARNING, E_USER_ERROR) and use trigger_error() instead of error_log().
http://php.net/manual/en/function.error-log.php
http://php.net/manual/en/function.trigger-error.php
http://php.net/manual/en/errorfunc.constants.php

With trigger_error(), errors will go to the log when they match the error_reporting level.  They can also be caught at runtime using set_error_handler() and inspected (backtrace, session state, etc.), displayed, emailed, or otherwise managed.
http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting
http://php.net/manual/en/function.set-error-handler.php

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
