### ISSUE TITLE
Using i-name (freexir) results in "OpenID authentication failed: Server denied check_authentication"

### ISSUE THREAD

**Issue by bjornbjorn** [openid/php-openid#28]
I downloaded the latest master today (14.09.2010) and tried to use my i-name in the /exmple/consumer/ script.

So I entered "=this*bjornbjorn" in the openID input box and was sent to https://authn.freexri.com/authentication/ (correct). After entering my password and clicking "Authenticate" there I'm sent back to /examples/consumer/ and the following error message appears:

"OpenID authentication failed: Server denied check_authentication"

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
