### ISSUE TITLE
WARNING: array_key_exists() expects parameter 2 to be array, null given in /usr/share/php/Auth/Yadis/Manager.php on line 40

### ISSUE THREAD

**Issue by GICodeWarrior** [openid/php-openid#30]
This warning is generated when the user has cookies disabled.

Auth/Yadis/Manager.php:40
    38     function get($name, $default=null)
    39     {
    40         if (array_key_exists($name, $_SESSION)) {
    41             return $_SESSION[$name];
    42         } else {
    43             return $default;
    44         }
    45     }

Backtrace
    1  array_key_exists(_yadis_services__openid_consumer_, ) called at [/usr/share/php/Auth/Yadis/Manager.php:40]
    2  Auth_Yadis_PHPSession->get(_yadis_services__openid_consumer_) called at [/usr/share/php/Auth/Yadis/Manager.php:474]
    3  Auth_Yadis_Discovery->getManager(1) called at [/usr/share/php/Auth/Yadis/Manager.php:443]
    4  Auth_Yadis_Discovery->cleanup(1) called at [/usr/share/php/Auth/OpenID/Consumer.php:440]
    5  Auth_OpenID_Consumer->complete() ...
    ...

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
