### ISSUE TITLE
SQLStore still makes use of PEAR DB

### ISSUE THREAD

**Issue by ccazette** [openid/php-openid#4]
It is clearly stated in the class comments that PEAR can be replaced with a class extending DatabaseConnection. This is for good, I don't have PEAR installed on my system and don't want to install it.
However, SQLStore still uses PEAR :
      function isError($value)
      {
              return PEAR::isError($value);
       }
I have set it to return FALSE at the minute as I am not too sure what to do (perhaps check for PEAR existence and if not check for parent isError() existence). Anyway, you can't get it to work if you don't have PEAR installed and even if so this function doesn't make sense.

Some class comments should be corrected as well, as sometimes it only refers to PEAR.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
