### ISSUE TITLE
examples/server/setup.php & SQLite broken

### ISSUE THREAD

**Issue by Lennie** [openid/php-openid#46]
It seems that setup.php generates the wrong configuration in SQLite.

It generates something like:
$s = new Auth_OpenID_SQLiteStore ('pathtosqlitedbfile');

While it should generate something similair to MySQL with:
require_once ('DB.php');

```
$db =& DB::connect($dsn);
```

Because Auth_OpenID_SQLiteStore expects a PEAR-DB-connection-object.

Hope this helps.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
