### ISSUE TITLE
stateless(dumb) mode

### ISSUE THREAD

**Issue by sunnyside** [openid/php-openid#49]
I think that I use the "Auth_OpenID_DumbStore" class when executing it with stateless(dumb) mode.
When Consumer.php line 618 is seen, it seems to do the association even when Auth_OpenID_DumbStore is used. 
Is this correct processing?

Consumer.php line 618

```
function Auth_OpenID_GenericConsumer($store)
{
    $this->store = $store;
    $this->negotiator = Auth_OpenID_getDefaultNegotiator();
    $this->_use_assocs = (is_null($this->store) ? false : true);   <-- it's true even if "Auth_OpenID_DumbStore"

    $this->fetcher = Auth_Yadis_Yadis::getHTTPFetcher();

    $this->session_types = Auth_OpenID_getAvailableSessionTypes();
}
```

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
