### ISSUE TITLE
Auth_OpenID_TrustRoot doesn't properly deal with 2 letter domains

### ISSUE THREAD

**Issue by ijansch** [openid/php-openid#55]
The Auth_OpenID_TrustRoot imlementation has an isSane method that assumes that all 2 letter domain names have at least 2 parts (e.g. .co.uk). This is a wrong assumption; the UK is one of the few 2 letter TLDs that has this feature. Others such as .nl, .de etc only have a single level.

This means that a site such as http://de.nl would be considered 'insane' as a trust root.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
