### ISSUE TITLE
De-couple Discovery from the Begin() process in Auth_Openid_Consumer

### ISSUE THREAD

**Issue by ccazette** [openid/php-openid#6]
It'd be better to have the initial Yadis discovery running in a separate method from the begin() method. That way you could still use this new discovery() method to check if the endpoint is valid without triggering the all authentication process. That would also allow to use a different discovery method.

A simple fix could be to rename have all the begin() logic in a discover() method, and have begin() calling this method and then calling beginWithoutDiscovery() if the endpoint is found or returning NULL if not.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
