### ISSUE TITLE
Call-time pass-by-reference is deprecated

### ISSUE THREAD

**Issue by ccazette** [openid/php-openid#8]
I am getting some PHP Errors as you cannot pass references in function like call_user_function() and call_user_function_array() anymore. It was a warning in PHP5, and it errors out in 5.3.

So '&' should be removed from :
- Consumer.php line 669
- Consumer.php line 1184
- Server.php line 1707
- TrustRoot.php line 416
- XRDS.php line 432
- Yadis.php line 144
- Manager.php line 416

And that's fixed !

**Comment by Woseseltops** [comment]
Just got this plugin working for PHP 5.5.9 with the patch above.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
