### ISSUE TITLE
Bug: AutoSubmitHTML form incorrectly urldecodes parameters.

### ISSUE THREAD

**Issue by coverprice** [openid/php-openid#81]
In Auth/OpenID/Message.php line 687:

<pre>
            $form .= sprintf(
                        "&lt;input type=\"hidden\" name=\"%s\" value=\"%s\" />\n",
                        $name, urldecode($value));
</pre>

urldecode() should not be used here. The values, if they are base64_encoded, will have any "+" characters replaced by a space character, and this breaks many things.

The solution is to replace urldecode with htmlentities, which will correctly escape the value for use in a HTML form.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
