### ISSUE TITLE
Bug Auth_OpenID::parse_str ignores values that contain '='

### ISSUE THREAD

**Issue by coverprice** [openid/php-openid#82]
If the parameter value contains an '=' sign, the parameter is ignored.

e.g. Auth_OpenID::parse_str('foo=xxxx=&baz=yyyy') will skip the 'foo' parameter because its value has a trailing '='.

This causes problems when some values are base64 encoded, because they may contain '=' symbols.

The solution is the following:
Auth/OpenID.php line 275:
old:  $pair = explode('=', $parts[$i]);
new: $pair = explode('=', $parts[$i], 2);

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
