### ISSUE TITLE
Documentation script fails with phpdoc

### ISSUE THREAD

**Issue by mravery** [openid/php-openid#85]
I am using phpDocumentor version 2.0.0a10. Using the `admin/makedoc.sh` script out of the box doesn't work. I need to modify the script like this:

```
phpdoc -p -t doc -d "Auth,admin/tutorials" --title "JanRain OpenID Library" --ignore "\*~,BigMath.php,Discover.php,CryptUtil.php,DiffieHellman.php,HMACSHA1.php,KVForm.php,Parse.php,TrustRoot.php,HTTPFetcher.php,ParanoidHTTPFetcher.php,PlainHTTPFetcher.php,ParseHTML.php,URINorm.php,XRI.php,XRIRes.php,Misc.php"
```

Note the different in synatx. The script should indicate what version of phpDocumentor ought to be used.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
