### ISSUE TITLE
can't get user information

### ISSUE THREAD

**Issue by farokojil** [openid/php-openid#86]
i'm trying to get user information after the authentication successes.
the task i have to register new users after log-in using openID in mysite,

i tried to do it in the consumer example:
in "finish_auth.php"  i found out that the variable "$sreg" hold the user information 
but after trying to get it from (yahoo-myspace) accounts it will return empty array and will return only the email using (wordpress) account.

so how can i do it?

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
