### ISSUE TITLE
Using PSR-0 compatible autoloader can't load all classes (& composer.json)

### ISSUE THREAD

**Issue by vmattila** [openid/php-openid#87]
php-openid library is currently a little bit unorganized in terms of the classes and their position in the file tree.

There are certain classes hidden in the "parent" file, like `\Auth_OpenID_AX_FetchResponse();` that requires Auth/OpenID/AX.php file. Complying with [PSR-0 autoloading standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md), it would be preferred that the class should reside in its own file (Auth/OpenID/AX/FetchResponse.php)

I have used to load php-openid with (similar to) following lines in the composer.json file:

``` json
"package": {
    "name": "openid/php-openid",
    "version": "dev-master",
    "source": {
        "url": "https://github.com/openid/php-openid",
        "type": "git",
        "reference": "39206ec13b29e43f8cf604158ac7d1530ec29ee1"
    },
    "autoload": {
        "psr-0": {
            "Auth_": "./"
        }
    },
    "include-path": ["./"]
}
```

Most of the classes work fine and no additional `require()` or `include()` calls are needed around application. However, Auth_OpenID_FetchResponse() is one that does not work.

Is there some reason that the code & classes are not organized in PSR-0 compliant way? Backwards compatibility? I am happy to contribute in the process of re-organization, if no issues come to your mind right away.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
