### ISSUE TITLE
Issue in trustRootValid function use

### ISSUE THREAD

**Issue by charlesmarais** [openid/php-openid#93]
Hi,

I think there is an error in the implementation and use of the function trustRootValid in the file Server.php.

The trustRootValid function can return true or false but can also return an Auth_OpenID_MalformedTrustRoot object.

trustRootValid is called twice in Server.php (line 1008 and line 757) and in both cases a control is performed using if(!trustRootValid()). The problem is that if trustRootValid returns an Auth_OpenID_MalformedTrustRoot object, the condition is not verified and the conditionnal instructions are not executed.

I think that the condition should be (for the call line 757) : 

<pre>        $trustRootValid = $r->trustRootValid();
        if ($trustRootValid === true) {
            return $r;
        }else if($trustRootValid instanceof Auth_OpenID_ServerError){
            return $trustRootValid;
        }else{
            return new Auth_OpenID_UntrustedReturnURL($message,
                                                      $return_to,
                                                      $trust_root);
        }
</pre>

Or something like that.

Do you agree with this analysis ? Do you experiment the same thing ?

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
