### ISSUE TITLE
Log error if php-xml isn't installed and it is needed for xrds

### ISSUE THREAD

**Issue by docwhat** [openid/php-openid#98]
I spent quite a few hours troubleshooting the code by hand because while my code worked great in development it failed on our production server.

It turned out to be due to the lack of php-xml being installed.

It would be really really really helpful if it was logged someplace that XRDS failed because php-xml wasn't installed.  Or better yet, a fatal error.

The symptoms were instead of hitting the following URLs on the openid server:
1. /
2. /xrds.xml
3. /users's url

It went:
1. /
2. /xrds.xml
3. /
4. /
5. /xrds.xml
6. /

I hope, at least, this bug report is useful for others.

Ciao!

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
